services:
  service:
    image: mallenomtest
    container_name: mallenom_backend
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    environment:
      - DB_HOST=mallenom_db
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=mallenom
      - DB_DATABASE=mallenom
    ports:
      - "5141:8080"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - files-volume:/app/storage
    networks:
      - mallenom-net
      
  database:
    image: postgres:alpine
    container_name: mallenom_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mallenom
      - POSTGRES_DB=mallenom
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    networks:
      - mallenom-net
    healthcheck:
      test: pg_isready -U user -d mallenom
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  data-volume:
  files-volume:
    
networks:
  mallenom-net:
